### ISSUE TITLE
Allow staff to acknowledge all notifications on Grading page

### ISSUE THREAD

**Issue by Aulud** [source-academy/frontend#1267]
## [UX] Allow staff to acknowledge all notifications on Grading page
Feature suggestion.

### Rationale

The backend generates a large amount of notifications for each staff member for student submissions, especially right after assessment deadlines, where all open submissions are auto-submitted and all submissions are re-autograded.

As a result, this renders a large number of submission badges at once in the submissions table (datagrid) on the Grading page. Each notification needs to be manually acknowledged by hovering over the corresponding badge and closing it with the 'X' button, which makes the notification system unnecessarily frustrating to use.

The submissions table also prioritises submissions with attached notifications, and sorts the submissions to float them to the top of the table. Acknowledging a notification removes it from that submission, which causes the datagrid to re-sort the submissions and re-render, crippling performance.

### Feature description

Add controls to allow staff greater flexibility in acknowledging submissions-related notifications, e.g. allow Avengers to acknowledge all notifications of a certain type for a given assessment at once. Alternatively, automatically acknowledge notifications when the corresponding submission has been viewed.

Last updated 16 Jun 2020, 11:45PM

**Comment by martin-henz** [comment]
Notifications are removed. issue gone.
