### ISSUE TITLE
Collate all notifications and controls into a notification mailbox

### ISSUE THREAD

**Issue by Aulud** [source-academy/frontend#1324]
## Collate all notifications and controls into a notification mailbox
UX feature suggestion.

### Rationale

The current notification system of Source Academy includes notifications for:
- new assessments released (students only)
- assessments near their deadlines (students only)
- new submissions, either by auto-submission at the assessment deadline or from a finalised submission (staff only)
- auto-graded submissions (students only)
- fully graded submissions (students only)
- un-submitted submissions (students only)

Currently, all student notifications are rendered beside the corresponding assessment, and the staff notifications are rendered beside the corresponding submission in the datagrid on the Grading page.

I propose we can collate all the notifications into a central mailbox to make it easier to manage. The mailbox would allow users to access the corresponding assessment or submission in a new tab by clicking on the notification (similar to how each assessment card rendered in the current `Profile` links to the assessment itself). This should also acknowledge the notification.

There are a couple additional benefits of the change:
- we can add controls for users to manage their notifications, e.g. filter by notification type/date, acknowledge all notifications of the same type (see PR #1267)
- we can consider removing the notification bubbles from the navigation bar, reducing visual clutter
- we can remove the notification bubbles from the submissions table on the Grading page - this significantly reduces the number of rendered elements in the datagrid and avoids the datagrid re-rendering each time a notification is acknowledged

Since a public Profile page for students is being worked on, I propose re-purposing the current `Profile` component into a notifications mailbox instead. As with the current `Profile` component, it will render above the Academy as a drawer component. The old `Profile` component will be left for reference for the Profile page.

If a UI mockup is required, I can add a wireframe for consideration.

Last updated 30 Jun 2020, 6:30PM

**Comment by martin-henz** [comment]
notifications have been removed. issue gone.
