### ISSUE TITLE
Game: Update GameUserStateManager

### ISSUE THREAD

**Issue by jetkan-yk** [source-academy/frontend#1438]
As mentioned in the PR #1437 , the retrieval of the user's achievement state requires changes to meet the new goal system.

https://github.com/source-academy/cadet-frontend/blob/0204b1fa9936fc59b8cd6584bfa1bbd4b2b4a449/src/features/game/state/GameUserStateManager.ts#L91-L97

**Comment by jetkan-yk** [comment]
Will update this as soon as the backend integration is ready

**Comment by anthony-halim** [comment]
#1436 centralised the stubbing to `Game.tsx`. Please replace the following lines instead.

https://github.com/source-academy/cadet-frontend/blob/master/src/pages/academy/game/Game.tsx#L15-L19

**Comment by anthony-halim** [comment]
Any update on this?

**Comment by jetkan-yk** [comment]
Still blocked by backend integration

**Comment by gok99** [comment]
Resolved by #1986
