### ISSUE TITLE
Make assessment workspace evaluation timeout configurable by question

### ISSUE THREAD

**Issue by angelsl** [source-academy/frontend#1669]
Some newer missions involve programs that run for longer (e.g. those involving the PIXNFLIX library).

We should make the assessment workspace evaluation timeout configurable by question, from the assessment XML, to allow for this.

(For the current semester, I just [raised the default limit](https://github.com/NUS-CS1101S/cadet-frontend/commit/3a94d76bbeb9d8d487b69ffe3dcb326bfedf785e).)

(This will need some minor backend changes as well.)

**Comment by martin-henz** [comment]
Fixed by #1979
