### ISSUE TITLE
Error with local cloned cadet-frontend when highlighting part of code

### ISSUE THREAD

**Issue by violinyap** [source-academy/frontend#1693]
TypeError: Cannot read property 'map' of undefined scopeForStatement

Error occurs whenever I highlight code in my local source academy. Paired usage with modules repository https://github.com/violinyap/modules

It might not happen directly but when you use it for sometime the error will appear.

<img width="1322" alt="Screenshot 2021-04-13 at 8 36 19 PM" src="https://user-images.githubusercontent.com/58291519/114553132-e885a700-9c97-11eb-8e8e-b08a20004991.png">

I tried removing all the map function that I have in my modules code, but the error still persists. Anyone knows why and how to fix this?

**Comment by martin-henz** [comment]
unlikely that this error is reproducible
