### ISSUE TITLE
Share button no longer preserves the chapter and variant

### ISSUE THREAD

**Issue by btzy** [source-academy/frontend#1704]
The title says it all.  It used to work at some point, but now it doesn't work.

**Comment by YaleChen299** [comment]
Hi, 
I have tested over this deployment https://source-academy.github.io/playground and it seems to work. 
Do you mind providing more details on how to reproduce this error? Thanks!

**Comment by btzy** [comment]
Hmm, it appears that chapters work now but not variants.

Steps to reproduce:
1. Open a new incognito window and go to https://source-academy.github.io, and wait for the playground to load.
2. Type something into the ace editor and select some chapter and variant (e.g. Source 2 Lazy).
3. Get the shareable link and copy it to clipboard.
4. Change the chapter to something else (e.g. Source 1).
5. Paste the shareable link into the address bar.
6. Observe that the notification shows the correct chapter and variant, but it is chapter is set back to Source 1 (with a flicker of the correct chapter and variant).  Sometimes it gets set to the correct chapter (Source 2), but the correct variant is never set.

https://user-images.githubusercontent.com/6948096/117529924-10ed9080-b00d-11eb-831b-f90a6c23673e.mp4

**Comment by martin-henz** [comment]
Here is a screenshot that shows the problem in Chrome.

![Uploading Screenshot 2021-05-27 at 12.59.25 PM.png…]()

**Comment by martin-henz** [comment]
Bumping this! Still an issue!
