### ISSUE TITLE
User profile cannot be closed on mobile

### ISSUE THREAD

**Issue by samuelfangjw** [source-academy/frontend#1813]
On smaller mobile screens, user profile cannot be closed once opened as the close button is hidden out of view.

<img alt="IMG_2590" width="40%" src="https://user-images.githubusercontent.com/60355570/122647100-1c2bf400-d155-11eb-8b3a-5e450eb899c6.PNG" />

Current env: Safari iOS, iPhone X.

**Comment by chownces** [comment]
With the removal of the grade metric in Rook, we will be making this drawer fixed width

**Comment by chownces** [comment]
Addressed in #1878
