### ISSUE TITLE
Display of long strings mess up the frontend

### ISSUE THREAD

**Issue by martin-henz** [source-academy/frontend#1857]
Example:
https://share.sourceacademy.org/4o52j

import { scrabble_list } from 'scrabble';
accumulate((x,y) => x + " " + y, "", scrabble_list);

brings the frontend into an inconsistent state:

<img width="1291" alt="Screenshot 2021-07-10 at 12 34 20 PM" src="https://user-images.githubusercontent.com/30220768/125151783-39177e00-e17b-11eb-87a8-5bb74b12acf6.png">

(editor - tool tabs layout problem)

Interestingly, the mobile version doesn't have this problem. So a recovery strategy is to make the browser small enough for the mobile version to kick in.

**Comment by chownces** [comment]
it seems to show up fine on MacOS Chrome, Safari and Firefox for me

![image](https://user-images.githubusercontent.com/53928333/125151419-8ba36b00-e178-11eb-84a5-03d50b46bd3c.png)

**Comment by martin-henz** [comment]
My Chrome version: Version 91.0.4472.114 
My OS: macOS Big Sur, Version 11.4

**Comment by martin-henz** [comment]
Firefox: no problem

**Comment by chownces** [comment]
I just updated to the Chrome and MacOS versions above, still cant seem to reproduce the issue. Could you try again after force refreshing the browser? (`cmd-shift-r`)

**Comment by martin-henz** [comment]
The problem persists in 
https://sourceacademy.org/playground (even after refreshing, also after cleaning browser cache and restarting browser)

Interestingly the problem is NOT present in
https://sourceacademy.nus.edu.sg/playground

**Comment by samuelfangjw** [comment]
<img width="1552" alt="Screenshot 2021-07-12 at 10 56 01 PM" src="https://user-images.githubusercontent.com/60355570/125309628-7db23d80-e364-11eb-8ad2-493a578db971.png">

I am unable to replicate this either.

Chrome version: Version 91.0.4472.114 (Official Build) (x86_64)
OS: macOS 11.4

**Comment by martin-henz** [comment]
Very strange. Let's maybe KIV this. I'll revisit in a few weeks, maybe it disappears by then, magically. After all, it also _a_ppears magically, it seems.

**Comment by martin-henz** [comment]
I cant reproduce this. Maybe I had an older version cached at the time.
