### ISSUE TITLE
SA@NUS: Help not customizable

### ISSUE THREAD

**Issue by martin-henz** [source-academy/frontend#1858]
Currently the help text has no effect:

<img width="865" alt="Screenshot 2021-07-10 at 10 39 55 AM" src="https://user-images.githubusercontent.com/30220768/125149406-7542e280-e16b-11eb-9d5d-fa89265aa19d.png">

<img width="865" alt="Screenshot 2021-07-10 at 10 40 51 AM" src="https://user-images.githubusercontent.com/30220768/125149415-7b38c380-e16b-11eb-97c5-4c89aa7bc4a9.png">

**Comment by martin-henz** [comment]
Markdown would be great!

**Comment by chownces** [comment]
Addressed in #1878
