### ISSUE TITLE
REPL in Assessment editor: "Run" does not clear the REPL

### ISSUE THREAD

**Issue by martin-henz** [source-academy/frontend#1875]
If there are error messages in the REPL, a new "Run" does not clear the messages.

**Comment by chownces** [comment]
Is there an example program? Or was this part of the testcase errors a few weeks back? The latter has been addressed and shldn't popup anymore.

**Comment by chownces** [comment]
Is there an example program? Or was this part of the testcase errors a few weeks back? The latter has been addressed and shldn't popup anymore.
