### ISSUE TITLE
Missing code/text in section 4.4.1

### ISSUE THREAD

**Issue by mark-friedman** [source-academy/frontend#1876]
There is missing code in [section 4.4.1](https://sourceacademy.org/sicpjs/4.4.1#p25).  There should be some more text after 
>For example, the query
`lives_near($x, list("Bitdiddle", "Ben"))` 
results in

**Comment by samuelfangjw** [comment]
Moving this issue to the frontend. Frontend did not account for snippets (which are not evaluated) having `JAVASCRIPT_OUTPUT` tags within them.

This issue affects other sections as well, but are less obvious. For example, 

<img width="709" alt="Screenshot 2021-07-28 at 1 04 00 PM" src="https://user-images.githubusercontent.com/60355570/127266631-1e3e3e85-4967-455b-a2bb-2a1c7c375d38.png">

for this snippet in chapter 3.2.3, the output of `W1(50);` is not displayed.

**Comment by martin-henz** [comment]
OK. You may want to check if you are handling all tags in https://github.com/source-academy/sicp/wiki#documenting-our-xml
Maybe there are tags that you  handle that are not documented, also. Let's try to have a consistent specs.

**Comment by martin-henz** [comment]
> Moving this issue to the frontend. Frontend did not account for snippets 
> (which are not evaluated) having JAVASCRIPT_OUTPUT tags within them.

Yes, I think the concept of the old web edition was to not show these because the user is supposed to click and play. But I think that's a bad idea. The online edition should show whatever the PDF edition shows.
