### ISSUE TITLE
redux state is exposed in production build

### ISSUE THREAD

**Issue by shenyih0ng** [source-academy/frontend#1962]
# Summary

With `redux-dev-tools` extension installed, it is possible to inspect the production redux state. 

This allows users to access: 

1. Auto grader test cases up to **hidden** (public and hidden test cases are exposed).
2. `editorPostpend` which in some cases exposes the answer (shown in the video below)
 
https://user-images.githubusercontent.com/47914880/133890828-ad55d00f-5e12-4f78-8421-9b18aadedd67.mov

_The video shows that the answer to this particular path can be retrieved from the redux state through `editorPostpend`_

## Possible fix

This is likely why introspection is exposed in production:

https://github.com/source-academy/frontend/blob/691baa22b7adee268ada8499ea1a373cd3e1085d/src/pages/createStore.ts#L17-L22
---

> I am not sure if this is an intended feature for debugging in the production build, but if it is in the case where this is not intended I would love to make a PR for it 😃

**Comment by angelsl** [comment]
> This allows users to access:
> 
>     1. Auto grader test cases up to **hidden** (public and hidden test cases are exposed).
> 
>     2. `editorPostpend` which in some cases exposes the answer (shown in the video below)

It's already possible to see this by just inspecting network requests to the backend anyway...

**Comment by chownces** [comment]
Just saw this, thanks for filing this issue! Closing this as the info is accessible through inspecting networks requests anyway. We have additional measures in place, such as backend-only testcases and manual grading by instructors/ avengers. The postpend should not contain answers for missions/ quests/ practical exams.
