### ISSUE TITLE
Character "&nbsp;" is being rendered to the reader

### ISSUE THREAD

**Issue by SeasonLeee** [source-academy/frontend#2076]
![image](https://user-images.githubusercontent.com/13610283/151105909-4ee7e8af-5891-4ac1-bd9d-df83f32c43c0.png)

As you can see from the screenshot presented above. And this is not the only place where this `&nbsp;` being rendered and I only screenshot this one for demonstration only. I believe it exist basically every pages since this character is being used everywhere.

(ps, I didn't know the issue of frontend goes into this repo so I created a same issue like this on in repo sicp, which is closed now.)

**Comment by martin-henz** [comment]
Fixed
