### ISSUE TITLE
Sentry blocked by adblockers

### ISSUE THREAD

**Issue by JoeyChenSmart** [source-academy/frontend#2174]
Seems like some ad-blockers might disable sentry entirely:
![image](https://user-images.githubusercontent.com/5654470/184117147-43cd3767-4078-4290-8354-77f8ae3766b0.png)

Not sure if this is a known issue, or there is some fix in place already.

Looks like there's a quick workaround from Sentry: https://docs.sentry.io/platforms/javascript/troubleshooting/#dealing-with-ad-blockers

**Comment by martin-henz** [comment]
The sentry docs say ad blocker "may cause your application to behave unexpectedly." What does that mean for us? What is the behavior of the system when an add blocker is in place? Is this affecting the functionality of the frontend, or is it just preventing the logging on the server?

**Comment by JoeyChenSmart** [comment]
AFAIK it won't affect any functionality other than the error logging, since the ad-blocker just prevents the frontend from sending requests to sentry's domain.

**Comment by RichDom2185** [comment]
This is a user choice (if they choose to not be tracked) – we can't do anything about it unless we want to self host all the ingest endpoints. Since the app isn't crashing when this happens, I feel we can just close this issue.
