### ISSUE TITLE
Mobile: Long dialog titles cause the generic dialog components to extend beyond the screen dimensions on mobile view

### ISSUE THREAD

**Issue by ianyong** [source-academy/frontend#2241]
The generic `ConfirmDialog` and `PromptDialog` components both suffer from this issue, which affects all existing dialogs where the title is fairly long.

![image](https://user-images.githubusercontent.com/5585517/196103708-77c7c14c-6ff5-4ff1-8967-bdca0f68ef0f.png)

**Comment by Johnwz123** [comment]
A similar issue can be observed for each of the assignment blocks, where the title, "Finalise Submission" and "Review Submission" cannot be seen.

![Image](https://github.com/source-academy/frontend/assets/112536096/74cc2530-6190-4a6e-b895-1ca321dcb427)
