### ISSUE TITLE
List of GitHub repositories shown when using GitHub to persist files is capped at 30

### ISSUE THREAD

**Issue by ianyong** [source-academy/frontend#2245]
Currently, a call is made to the `https://api.github.com/user/repos` endpoint to retrieve the list of repositories that a user has access to when the `Open` or `Save As` buttons are clicked:
![image](https://user-images.githubusercontent.com/5585517/198825346-3ac68555-36e3-480c-9236-927087e05206.png)

However, the API only returns 30 results by default (see https://docs.github.com/en/rest/repos/repos#list-repositories-for-the-authenticated-user). As such, not all repositories are listed.

**Comment by ianyong** [comment]
We should be able to retrieve all user repositories using the [octokit.js pagination API](https://github.com/octokit/octokit.js#pagination). The main issue is that testing the changes locally [requires privileged access to the Source Academy organisation](https://github.com/source-academy/frontend/wiki/GitHub-Integration:-Initial-Set-up).

**Comment by martin-henz** [comment]
I've made you "owner" of source-academy, @ianyong . Does that help?

**Comment by ianyong** [comment]
> I've made you "owner" of source-academy, @ianyong . Does that help?

Yes, that helps, thank you! I have a fix up and tested (#2250), but I need to clarify with the person who wrote the original error handling code on its intended behaviour (see [here](https://github.com/source-academy/frontend/pull/2250#issuecomment-1303175888)).
