### ISSUE TITLE
Syntax highlighting of undefined

### ISSUE THREAD

**Issue by johannesborgstrom** [source-academy/frontend#2248]
In the editor, the builtin "undefined" is shown with the same colour as user-defined names.
It should be highlighted as the other primitive values (true, false, numerals, ...), making it stand out more.

**Comment by martin-henz** [comment]
Yes, we need to think about this. A small complication: In JavaScript (and therefore in Source) undefined is not a keyword like true and false. Instead, it's a predeclared name that refers to the value undefined. We should think a bit more what the colors should represent in the stepper...

**Comment by johannesborgstrom** [comment]
(in the editor.)
I think undefined and NaN are special enough for an exceptional rule, in analogy with (the reserved word) null.

**Comment by martin-henz** [comment]
Unfortunately highlighting undefined like a keyword would add confusion rather than remove confusion. Students need to be aware that it's a name:
```
function f(undefined) {
    return undefined;
}
f(1); // returns 1
```
