### ISSUE TITLE
Environment Visualizer incorrectly shows function as being called twice

### ISSUE THREAD

**Issue by XenonShawn** [source-academy/frontend#2256]
The following code snippet:

```
function create(n) {
    const arr = [];
    let x = 0;
    
    while (x < n) {
        arr[x] = () => x;
        x = x + 1;
    }
    
    return arr;
}

create(3)[1]();
```

Results in the following environment:

![image](https://user-images.githubusercontent.com/57314121/202653979-5372aced-ec7a-47a8-a3a8-875589d19057.png)

Which is incorrect as the `create` function is only called once.

**Comment by martin-henz** [comment]
Yes, that's an issue. Here is a share link:
https://share.sourceacademy.org/wgmf3
(breakpoint on "true;")

**Comment by martin-henz** [comment]
Fixed by new explicit control evaluator.
