### ISSUE TITLE
All workspaces make use of the same breakpoints state

### ISSUE THREAD

**Issue by ianyong** [source-academy/frontend#2268]
When the user changes workspace, the state of the breakpoints set remains the same as the last workspace in which the user added or removed a breakpoint. This can be confusing to the user if they have not set any breakpoints in the new workspace as the breakpoints are not displayed in the editor of the new workspace, yet are hit when run.

An example to replicate this is:
1. Make use of a version of the Source Academy with access to at least 2 workspaces. The NUS version of the Source Academy is ideal for this.
1. Write a Source 3+ program in any workspace (say the playground).
1. Write another Source 3+ program in another workspace (say Sourcecast). This program should have at least as many lines as the previous program. For simplicity, we can use the same program for both workspaces.
1. In either of the workspaces, set at least one breakpoint.
1. Switch over to the other workspace **without leaving the browser page**. This is because the breakpoints state will be cleared on refresh.
1. Set the language to Source 3+.
1. Run the program. The program will be evaluated as if the breakpoints set in the previous workspace exist in the current workspace.

**Comment by martin-henz** [comment]
Yes, this is a recurring problem.

The current breakpoints should be part of the editor state, along with the current viewing window.

**Comment by ianyong** [comment]
Should have been closed by #2269.
