### ISSUE TITLE
Mobile keyboard steals focus from underlying text container

### ISSUE THREAD

**Issue by ianyong** [source-academy/frontend#2276]
The `MobileWorkspace` component has a `MobileKeyboard` for inputting commonly used character(s) in Source. However, clicking on the mobile keyboard makes the underlying text container (be it the editor or the REPL) lose focus because the mobile keyboard gains focus from being clicked on.

![vmconnect_sXn9Et2Tyq](https://user-images.githubusercontent.com/5585517/207343224-c6103c7a-fc1e-43f0-98eb-71442175a3a5.gif)

In the screen capture above, it can be seen that the editor loses focus when the mobile keyboard is clicked on (as indicated by the cursor no longer blinking).

**Comment by martin-henz** [comment]
Bug seems to be gone now. Checked by @martin-henz on Android (Samsung Galaxy) and Joven (iPhone 13).
