### ISSUE TITLE
Grading: Assessment briefing not accessible while grading

### ISSUE THREAD

**Issue by martin-henz** [source-academy/frontend#2310]
The grading workspace should have the Assessment Briefing so that the grader can read the briefing while grading. The Briefing should be accessible using the briefcase icon, like in the student view of the assessment.

<img width="954" alt="Screen Shot 2023-01-13 at 11 54 12 AM" src="https://user-images.githubusercontent.com/30220768/212234449-4ed21c58-b105-4a0f-a2f6-6a41af55c07e.png">

**Comment by zohreab** [comment]
To have the mission briefing for the grading workspace, it is essential to access the Long summary of the assessment in the GradingWorkspace.tsx on the frontend side. This can be achieved by extracting the data using the submission_id. Consequently, modifications are required in the admin_grading_view.ex on the backend side. The long summary of the assessment should be incorporated into this file to ensure its content is available within each submission for every student.
