### ISSUE TITLE
Upgrade react-scripts

### ISSUE THREAD

**Issue by chownces** [source-academy/frontend#2313]
- for Node v18 compatibility (https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported/71334532#71334532)

Alternatively,:
- consider shifting out of CRA
  -  e.g. migrating to vitejs
  - CRA is not as actively maintained anymore

**Comment by ianyong** [comment]
This would also allow us to remove the following hack:
https://github.com/source-academy/frontend/blob/46ade71e85c5dfcf478f906ed62201667c97aced/package.json#L133-L136

See #2214 for context.

**Comment by ianyong** [comment]
> Unfortunately, we cannot upgrade `react-scripts` (CRA) to v5.0x because another dependency that we use, Create React App Configuration Override (CRACO) does not have a stable version that supports CRA v5.x yet

It seems that this is no longer true with the release of [CRACO v7](https://github.com/dilanx/craco/releases/tag/v7.0.0), so we might be able to fully resolve the issue in #2214 as well as update Node.js once we upgrade `react-scripts`.
