### ISSUE TITLE
Build does not work on NodeJS V17+

### ISSUE THREAD

**Issue by Cloud7050** [source-academy/frontend#2330]
There is room for futureproofing building the frontend, while we are still on Node V16.

Node V17 introduces a breaking change that fixes a security issue with the SSL provider. While building with the current code as is, this error is encountered:

```
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\ ... \node_modules\webpack\lib\util\createHash.js:135:53)
    ...
    at C:\ ... \node_modules\react-scripts\node_modules\babel-loader\lib\index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

I am not sure what a proper fix entails, but it may be as simple as updating the relevant packages we use that implement the required security fixes.

A bandaid fix that skirts around the issue is to edit the node options in the `package.json` scripts, adding the `--openssl-legacy-provider` flag. Ie, for the `build` script, changing it to `NODE_OPTIONS=\"--max_old_space_size=8192 --openssl-legacy-provider\"`, and for the `start` script, specifying something like `cross-env NODE_OPTIONS=--openssl-legacy-provider EXTEND_ESLINT ...`.

---

Along the way, I encountered another issue:

```
You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize({ 'lib/mappings.wasm': ... }) before using SourceMapConsumer
```

I found that a workaround is to add the `--no-experimental-fetch` flag to the `build` script. Ie, its node options now looks something like `NODE_OPTIONS=\"--max_old_space_size=8192 --openssl-legacy-provider --no-experimental-fetch\"`.

It is important to note that these are not full solutions, but are just to quickly get the frontend built and running for local testing on a newer Node version.

**Comment by Yongbeom-Kim** [comment]
I cannot reproduce this issue, and https://github.com/source-academy/frontend/issues/2313 resolves it? I think we can close this issue
