### ISSUE TITLE
Refactoring of names broken - editor's previous state not accounted for with multicursor/undo/redo

### ISSUE THREAD

**Issue by Cloud7050** [source-academy/frontend#2337]
The playgrounds in both the SA and NUS deployments currently have the issues described below. I am unsure if it is related to the merging of PR #2331, which quickly addressed a critical bug with editor keystrokes and state, as I do not know what version each deployment is currently running (ie when the issues started).

Certain actions performed in the editor cause the cursor position(s) and selected text to bug out; I have encountered multicursor behaviour being broken, which in turn breaks the refactoring of multiple name occurrences. Undoing/redoing also does not behave as expected.

I suspect that the editor is unable to properly make use of its previous state from before an affected action was performed. To correctly perform the action, it needs to take the previous cursor(s) and selection(s) into account, thus knowing where the cursor(s) should then be and what text it should then be selecting. The current behaviour is as if the initial application of the action "deletes" all previous text, and replaces it with a "paste" of the new displayed text.

Interestingly, these issues do not occur with the homework editor as opposed to the playground editor. Source/JavaScript language settings also do not appear to affect this. In relation to #2332, this was all tested on desktop.

---

When using multiple cursors and pressing a keystroke, the keystroke is only correctly applied to the last instance of selected text or cursor position in the file. The cursor then gets placed at the end of the file, which is where subsequent applications take place. After that, further keystrokes cause 2 applications at the end of the file.

Refactoring variable name occurrences (Ctrl+M) makes use of multicursor and is thus similarly impacted.

To demonstrate, in the images below, I refactor `variable` by having all 6 occurrences selected with a cursor at the end of each (via Ctrl+M):

![image](https://user-images.githubusercontent.com/44526554/215922045-16b2e1cf-ca62-4977-98d2-dc2726465137.png)

I then type `name`. The last instance of selected text is replaced by `n`, the cursor gets placed at the end of the file, and the remaining 5 `n`s are placed there. The rest of the letter keystrokes are applied only twice, in the same place:

![image](https://user-images.githubusercontent.com/44526554/215922172-9488bbdb-fb47-4a78-9036-04cc638bfd93.png)

It is instead expected that the cursors remain in place, and the keystrokes replace the selected text or are inserted at the cursor(s). Here is a depiction from the NUS deployment's homework editor:

![image](https://user-images.githubusercontent.com/44526554/215923947-fcfb557b-23f3-416a-8e4e-406919bb3a41.png)

---

When undoing (Ctrl+Z) or redoing (Ctrl+Shift+Z), all the text in the editor gets selected and the cursor is placed at the end of the file. This behaviour bears resemblance to how multicursor is being impacted.

Initial cursor position and text:

![image](https://user-images.githubusercontent.com/44526554/215924268-83cb58d7-393c-4344-a1cc-a24ab2d1f50e.png)

After undo:

![image](https://user-images.githubusercontent.com/44526554/215918545-f1c3bde9-7f3b-47d4-a275-a1e4025883ef.png)

After redo:

![image](https://user-images.githubusercontent.com/44526554/215918569-5722448c-4517-4d02-9c1f-cb8050af5609.png)

It is instead expected that the cursor jumps to the specific place where text was removed, or selects the inserted text with the cursor placed at its end, as the case may be:

![image](https://user-images.githubusercontent.com/44526554/215924309-4381e7cc-9cc8-4daa-9e97-d3645aa940d7.png)

![image](https://user-images.githubusercontent.com/44526554/215924703-27f8c687-1dc2-48a1-a249-9814e6787770.png)

**Comment by ianyong** [comment]
> The playgrounds in both the SA and NUS deployments currently have the issues described below. I am unsure if it is related to the merging of PR #2331, which quickly addressed a critical bug with editor keystrokes and state, as I do not know what version each deployment is currently running (ie when the issues started).

#2331 has not been deployed to SA@NUS - you can verify this by replicating the issue via the steps in the issue linked to #2331. Either way, from what you've described, memoizing the side content components is definitely not the source of the bug because it would affect all workspaces, and not just the playground.

Anyway, I looked into this issue further and determined that #2257 introduced this regression. This was done by binary searching the git history and attempting to replicate the issue in a local development environment, with emphasis given to changes that touch the playground (based on the observation that this issue is only present in the playground).

To be very clear, this issue has nothing to do with #2331 and #2332 at all. Those issues deal with unnecessary re-rendering and should not affect correctness, only performance.

**Comment by Cloud7050** [comment]
Adding another observation: Each editor keystroke resets the scroll position of the REPL's output component at the bottom right.

**Comment by ianyong** [comment]
After a lot of time tracing code, I've narrowed down the offending commit to https://github.com/source-academy/frontend/pull/2257/commits/037d9c957e22a8097660b5f76a214553fddebf04.
