### ISSUE TITLE
"Source Academy is down" BUG

### ISSUE THREAD

**Issue by larrywang0701** [source-academy/frontend#2365]
Hello everyone:
There is a bug that I encountered last semester in CS1101S, and some of my friends also encountered this.
This bug is about when opening "https://sourceacademy.nus.edu.sg" and also "sourceacademy.org", a brower's default error page is shown
![image](https://user-images.githubusercontent.com/113608053/222398504-fd865dc5-783a-4d78-a66d-59b139988689.png)
![image](https://user-images.githubusercontent.com/113608053/222404102-8849a70d-8713-4477-a36a-b93f1ff18647.png)

**How to trigger**
No exact 100% way to trigger this bug yet found, but this occasionally occurs when I try to access Source Academy.
It happens today again during my meeting with Prof. Martin.
Platform: Windows 10
Browser: MS Edge version 109.0.1518.78
Network: NUS_STU WIFI
**Checks:**
Refresh and deep refresh (ctrl+shift+r) do not work
Open in a new tab do not work
Able to access any other website (tested with www.google.com, www.github.com and NUS Canvas) at the same time so it's not due to my own network error (I wrote and submitted this issue and refreshed source academy's broken page again and again at the same time)
**How to temporily solve**
Open a new "in private mode" tab in current browser and open https://sourceacademy.nus.edu.sg in the in private tab.
Use another browser.
Click on the three-dots button on the right corner of MS Edge and click the "Exit Edge" button at the bottom of the pop list or use Task Manager to forcefully end Edge processes and all related sub processes then reopen MS Edge seems can sometimes fix this issue but sometimes not.

This issue might related to brower's cache with source academy frontend, and it may interrupt students when they wanna try to login and do their assessments, saying that "Source Academy is down!"

**Comment by RichDom2185** [comment]
We can't seem to reproduce this. If this happens again, perhaps we can reopen the issue. Otherwise, I'll close this for now.
