### ISSUE TITLE
Update React types to v18

### ISSUE THREAD

**Issue by ianyong** [source-academy/frontend#2384]
In #2376, the `@types/react` package was forced to use v17 instead of v18 via [selective dependency resolution](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/), This is because it introduced breaking type changes. See [here](https://blog.logrocket.com/upgrading-react-18-typescript/#react18-breaking-type-changes) for more information.

For the long-term maintenance of the Source Academy, it would be good if we can resolve these breaking type changes and bump `@types/react` to v18.

**Comment by chownces** [comment]
Closed by #2504
