### ISSUE TITLE
Tooltips on disabled buttons do not go away on Chromium browsers

### ISSUE THREAD

**Issue by ianyong** [source-academy/frontend#2417]
This is not an issue on Firefox.

![image](https://user-images.githubusercontent.com/5585517/229507022-3e5aa166-ae4c-4bbf-b9f6-bfdf7be75063.png)

**Comment by martin-henz** [comment]
Some discussion of this: https://github.com/ant-design/ant-design/issues/9581
not sure if this helps.

**Comment by ianyong** [comment]
> Some discussion of this: [ant-design/ant-design#9581](https://github.com/ant-design/ant-design/issues/9581) not sure if this helps.

Thank you! I managed to fix it by using an `AnchorButton` instead of a `Button` for the control buttons. Detailed explanation in the upcoming PR.
