### ISSUE TITLE
Sessions: Join arrow button not working

### ISSUE THREAD

**Issue by martin-henz** [source-academy/frontend#2422]
<img width="1003" alt="Screen Shot 2023-04-04 at 11 45 21 AM" src="https://user-images.githubusercontent.com/30220768/229682210-b43ad436-5c19-4ac0-9950-9d442774bae1.png">

This button does not seem to work. The expected behavior (I guess) is that the entered session key becomes activated. This is not the case. Instead the user needs to hit "return" inside the text entry field for the session key.

(Chrome on mac)

**Comment by shenyih0ng** [comment]
related to #2417, the switch to `AnchorButton` affects buttons with `type = submit` props

<img width="702" alt="image" src="https://user-images.githubusercontent.com/47914880/233608954-e064a1d5-5d0e-427f-87a7-cf5afe5e560c.png">
