### ISSUE TITLE
SICP JS: spaces in auto-complete

### ISSUE THREAD

**Issue by martin-henz** [source-academy/frontend#2432]
<img width="606" alt="Screen Shot 2023-04-09 at 10 09 46 PM" src="https://user-images.githubusercontent.com/30220768/230777755-13ecdbfe-eac3-4356-b8da-f9eaa3910161.png">

The auto-complete results should preserve the spaces in the original.

**Comment by yiwen101** [comment]
Should be fixed with sicp/pull/885 and  frontend pull #2436
