### ISSUE TITLE
SICP JS: punctuation and spaces missing in search result

### ISSUE THREAD

**Issue by martin-henz** [source-academy/frontend#2433]
<img width="583" alt="Screen Shot 2023-04-09 at 10 19 16 PM" src="https://user-images.githubusercontent.com/30220768/230778209-2cfb3e7a-ea45-4d51-8b8b-bda87f9c24bb.png">

**Comment by quantavoid11** [comment]
Hey @martin-henz , can I work on this issue?

**Comment by martin-henz** [comment]
This PR https://github.com/source-academy/sicp/pull/885 took care of this issue. But this closely related issue is not handled yet: https://github.com/source-academy/frontend/issues/2432

@quantavoid11 feel free to take a look, but note that this is @yiwen101 's term project at NUS, so he might have priority in handling this issue :)
