### ISSUE TITLE
SICP JS: add section information to search results

### ISSUE THREAD

**Issue by martin-henz** [source-academy/frontend#2434]
<img width="558" alt="Screen Shot 2023-04-09 at 10 23 54 PM" src="https://user-images.githubusercontent.com/30220768/230778408-9adc06a2-a9de-4be8-8ff1-622b2f0f5c6a.png">

Instead of bullet points, we should indicate the section, such as

Foreword: Primitive means...

1: However it is the ability...

1.1.2: Constant declaration...

**Comment by yiwen101** [comment]
added in #2486
