### ISSUE TITLE
Scheme/Python/Source button: should say "JavaScript" instead of "Source"

### ISSUE THREAD

**Issue by martin-henz** [source-academy/frontend#2448]
The button is wrongly named. We support "Full JavaScript", "Full TypeScript", HTML, etc.

Best we use "JavaScript" as label instead of "Source". JavaScript encompasses most of the functionality of that option.

**Comment by s-kybound** [comment]
Hi, this should be resolved with PR https://github.com/source-academy/frontend/pull/2449
