### ISSUE TITLE
Python: not working

### ISSUE THREAD

**Issue by martin-henz** [source-academy/frontend#2450]
<img width="717" alt="Screen Shot 2023-04-15 at 3 12 51 PM" src="https://user-images.githubusercontent.com/30220768/232194593-62b29898-41ee-4f3f-8fe6-142abe058a82.png">

**Comment by Fidget-Spinner** [comment]
Python S1 works. Python S2-4 don't work and should be disabled (for now) as they aren't in js-slang or py-slang yet.
