### ISSUE TITLE
Remove 'disabled periods' feature

### ISSUE THREAD

**Issue by chownces** [source-academy/frontend#2506]
We can disable a frontend deployment of Source Academy via the `.env` configuration for users with the `student` role.

Previously, this was used to disable the NUS and public deployments during examinations, under the assumption that students cannot have the `staff` or `admin` role.

However, anyone can be `staff` or `admin` by creating a new course (even in the disabled configuration), and circumvent the disabled configuration.

Would we still be using the disable feature in the future? If so, more safeguards need to be in place to ensure students cannot access the academy during disabled periods. Else we can remove this feature entirely if unused @martin-henz

**Comment by martin-henz** [comment]
Need to check with the teaching team. Will get back on this.

**Comment by martin-henz** [comment]
The authoritative answer from Prof Kok Lim: 

We probably had "taken down" Source Academy for the Reading Assessments in 2018 and/or 2019, but have not done that subsequently. I don't think we need this feature anymore.

**Comment by martin-henz** [comment]
So I think we can safely remove this feature.

**Comment by martin-henz** [comment]
Yes, now that SA is multi-tenant and used by places outside of NUS, we shouldn't have a feature that globally disables the frontend for all users, I think.

I'm proposing to permanently remove this feature. Details of the feature are in the README here: https://github.com/source-academy/frontend#disable-periods
