### ISSUE TITLE
Migrate BlueprintJS OverlayToaster Component

### ISSUE THREAD

**Issue by chownces** [source-academy/frontend#2529]
BlueprintJS v4 [OverlayToaster](https://github.com/palantir/blueprint/blob/develop/packages/core/src/components/toast/toaster.tsx) uses the deprecated `ReactDOM.render`.

We are currently working around it with these temporary changes (https://github.com/source-academy/frontend/pull/2504/commits/f3c4d767bd246c64fde223d21f8b1973deca1d74).

BlueprintJS might only deprecate the usage of `ReactDOM.render` in v6.

This issue seeks to track the BlueprintJS updates and to remove the above workaround once the new BlueprintJS API is ready

**Comment by RichDom2185** [comment]
BlueprintJS v5.9+ supports this now. See https://github.com/palantir/blueprint/issues/5212#issuecomment-1881229199 for the solution.
