### ISSUE TITLE
Env Viz: Avoid trivial steps

### ISSUE THREAD

**Issue by martin-henz** [source-academy/frontend#2535]
Example:
<img width="661" alt="Screen Shot 2023-06-28 at 7 01 33 PM" src="https://github.com/source-academy/frontend/assets/30220768/00b452bc-bf90-46fc-92da-8947dd095458">
<img width="661" alt="Screen Shot 2023-06-28 at 7 01 49 PM" src="https://github.com/source-academy/frontend/assets/30220768/a2978c61-5b80-4195-87da-246f3e2b4dae">
<img width="661" alt="Screen Shot 2023-06-28 at 7 01 58 PM" src="https://github.com/source-academy/frontend/assets/30220768/5be1b565-844f-4af8-a3cf-4a52e46c6a8b">
<img width="661" alt="Screen Shot 2023-06-28 at 7 02 14 PM" src="https://github.com/source-academy/frontend/assets/30220768/5053dc31-ffe9-4827-84e8-b168f225d617">
Step 2 has no change compared to Step 1. It should be avoided.

Step 3 has only a semicolon removed, compared to the previous step. We should avoid such a trivial step.

**Comment by martin-henz** [comment]
This issue seems to be solved already. @dickongwd @vansh284 can you check and close the issue?

**Comment by vansh284** [comment]
Closed by https://github.com/source-academy/js-slang/pull/1436
