### ISSUE TITLE
Env Viz: Avoid trivial step at the end

### ISSUE THREAD

**Issue by martin-henz** [source-academy/frontend#2536]
Example:
<img width="963" alt="Screen Shot 2023-06-28 at 7 09 39 PM" src="https://github.com/source-academy/frontend/assets/30220768/57d430b7-b2eb-4bf5-8536-9c7e0fb92760">
<img width="963" alt="Screen Shot 2023-06-28 at 7 09 46 PM" src="https://github.com/source-academy/frontend/assets/30220768/02124fed-d908-458c-a01b-75ebb81815ea">
<img width="963" alt="Screen Shot 2023-06-28 at 7 09 57 PM" src="https://github.com/source-academy/frontend/assets/30220768/070f23cb-5659-47d9-8967-f8564b2a7f42">

Steps 7 and 8 are the same. One of them is redundant.

**Comment by martin-henz** [comment]
This issue seems to be solved already. @dickongwd @vansh284 can you check and close the issue?

**Comment by vansh284** [comment]
Closed by https://github.com/source-academy/js-slang/pull/1436
