### ISSUE TITLE
Env Viz: Avoid pushing unnecessary ENVIRONMENT instruction

### ISSUE THREAD

**Issue by martin-henz** [source-academy/frontend#2538]
If there is already an ENVIRONMENT instruction on top the agenda, it's not necessary to push another one: it will not have any effect. Example:

<img width="1029" alt="Screen Shot 2023-06-28 at 9 48 58 PM" src="https://github.com/source-academy/frontend/assets/30220768/31f29a9a-d51d-4b35-929f-5fddf0c49266">

**Comment by vansh284** [comment]
Along the same lines, if there are no declarations in the block I believe there is no need for an ENVIRONMENT instruction either, do you agree? @martin-henz  
![image](https://github.com/source-academy/frontend/assets/65393463/f0d2b634-edfb-45d7-b29e-dedf5f89dd49)

**Comment by martin-henz** [comment]
This issue seems to be solved already. @dickongwd @vansh284 can you check and close the issue?

**Comment by vansh284** [comment]
Closed by https://github.com/source-academy/js-slang/pull/1436
