### ISSUE TITLE
Env Viz: Inconsistent steps

### ISSUE THREAD

**Issue by martin-henz** [source-academy/frontend#2539]
In this example, stepping forward, Step 12 is this:
<img width="1029" alt="Screen Shot 2023-06-28 at 10 05 36 PM" src="https://github.com/source-academy/frontend/assets/30220768/0fee9936-86a7-424f-93ed-4cbbe0f4192f">
but stepping backward, Step 12 is this:
<img width="1029" alt="Screen Shot 2023-06-28 at 10 05 49 PM" src="https://github.com/source-academy/frontend/assets/30220768/8edde728-5225-429a-a9bd-ac94903dc89a">

**Comment by martin-henz** [comment]
This issue seems to be solved already. @dickongwd @vansh284 can you check and close the issue?

**Comment by vansh284** [comment]
Closed by https://github.com/source-academy/js-slang/pull/1436
