### ISSUE TITLE
Alternative editor bindings (vim/emacs) do not work

### ISSUE THREAD

**Issue by dickongwd** [source-academy/frontend#2543]
The editor's key bindings are unchanged/not affected when switching editor binding options.

<img width="695" alt="image" src="https://github.com/source-academy/frontend/assets/57355025/64fdc995-d22d-43e2-b676-c040c8d43f04">

**Comment by chownces** [comment]
Thanks for catching this. Here's the offending commit: 83334d5c (related to code splitting)
