### ISSUE TITLE
Remove the disable-frontend feature

### ISSUE THREAD

**Issue by martin-henz** [source-academy/frontend#2648]
Now that SA is multi-tenant and used by places outside of NUS, we shouldn't have a feature that globally disables the frontend for all users, I think.

I'm proposing to permanently remove this feature. Details of the feature are in the README here: https://github.com/source-academy/frontend#disable-periods

**Comment by sayomaki** [comment]
Might be already mentioned in #2506, but so far no updates from that issue.

**Comment by martin-henz** [comment]
Thanks. Closing this one, and renaming https://github.com/source-academy/frontend/issues/2506
