### ISSUE TITLE
Game: Save game state for staff and admin

### ISSUE THREAD

**Issue by martin-henz** [source-academy/frontend#2649]
Currently the game data is saved only for students, not for staff or admin.

This should be changed so that staff and admin have the same game experience, keep up-to-date on the game development and spot issues.

**Comment by lhw-1** [comment]
The relevant code snippet is [here](https://github.com/source-academy/frontend/blob/master/src/features/game/save/GameSaveRequests.ts#L15-L17) - I am wondering if this was an oversight during development (and hence can be resolved by simply removing this check), or if this feature was specifically limited to students for a reason.

Currently, the `game_states` JSON object (the save file for the game, essentially) is stored under the course, so there shouldn't be any conflicts between save states for staff / admin users. We can investigate this further to see if there are any potential conflicts.

**Comment by RichDom2185** [comment]
Embedding the snippet here for easy reference:

https://github.com/source-academy/frontend/blob/f1d3cba0a13c7459106a1f2801437c94c68f3d4a/src/features/game/save/GameSaveRequests.ts#L15-L17

> ...or if this feature was specifically limited to students for a reason.

Looking at the code, I don't think this is the case, at least not anymore. It should be safe to just remove this check – in the unlikely worst case, there might be some unknown bug with staff/admin (which we would not expect to play the game much anyway).

**Comment by martin-henz** [comment]
The system is now quite gracefully degrading on this example. Here is the link:
https://share.sourceacademy.org/htl4m
Of course with rediculously large settings, Source Academy brings the browser down to its knees.
