### ISSUE TITLE
Grading: Filtering grading table by group does not work

### ISSUE THREAD

**Issue by RichDom2185** [source-academy/frontend#2692]
Typing a group in the grading search bar does not filter correctly:

<img width="433" alt="image" src="https://github.com/source-academy/frontend/assets/34370238/f26f8ddd-e36e-45f0-b1db-eff10ee532cb">

* Expected: filters entries by anything that matches the search query
* Actual: Does not seem to check the group field for matching entries (resulting in no results found assuming the search query is only present in the "Group" column)

---

Clicking a group from a table entry does correctly add (and apply) the filter, though:

<img width="196" alt="image" src="https://github.com/source-academy/frontend/assets/34370238/855dc523-7546-4ab2-8cd0-5395e9ab1b3c">

**Comment by InfinityTwo** [comment]
@RichDom2185 We aren't able to replicate this issue, but it may just be an unclear issue. Could you check if this still exists and if so, could you give us a more detailed explanation of the error?

**Comment by RichDom2185** [comment]
> @RichDom2185 We aren't able to replicate this issue, but it may just be an unclear issue. Could you check if this still exists and if so, could you give us a more detailed explanation of the error?

I just tested again, seems to be fixed now. Probably some bug with the library that fixed itself in one of the commits since this issue was created. Thanks and sorry for the trouble!

I'll proceed to close the issue now.
