### ISSUE TITLE
Grading UI/UX: Grading Overview Showing X Entries Per Page Incorrect

### ISSUE THREAD

**Issue by thortol** [source-academy/frontend#2823]
The showing X entries per page drop down box has a bug where it only shows 10 entries no matter what value is selected.
![image](https://github.com/source-academy/frontend/assets/52688525/cdf44de8-66ac-4261-a5f1-6f417d4884f2)
![image](https://github.com/source-academy/frontend/assets/52688525/619dd4e1-a4e1-4a92-b9c9-1e854c1b6cc5)

**Comment by InfinityTwo** [comment]
the feature was added by #2787, which is the most likely cause of the bug
