### ISSUE TITLE
Run button not working on mobile devices

### ISSUE THREAD

**Issue by JovenSoh** [source-academy/frontend#2839]
After a recent update to the mobile version of source academy, the run button in the playground no longer works. Clicking run does not run the code, there is no output either. 

<img width="311" alt="image" src="https://github.com/source-academy/frontend/assets/34702990/93c7c4b8-f385-4c6b-a7d2-787d5c128737">

**Comment by sayomaki** [comment]
This appears to be a regression from #2688 where the side content has been refactored to use sagas instead. Executing code from the mobile workspace is slightly different from desktop as it does not directly trigger `evalCode` when clicked, but instead relies on the changing tab functionality (the run button is considered a "tab") to call the code execution routine. Maybe @leeyi45 can give some advice on what is the best way to handle this?

**Comment by leeyi45** [comment]
Is that the exact functionality? Code is evaluated when the current tab is changed?
