### ISSUE TITLE
Remove Sourcecast and Sourcereel

### ISSUE THREAD

**Issue by martin-henz** [source-academy/frontend#2840]
@sayomaki @boydanderson and I discussed and propose that we remove the features `sourceCast` and `sourceReel` from the frontend and the backend. This will allow us to focus the development effort more and reduce the complexity of the system.

**Comment by RichDom2185** [comment]
I discussed this with Prof @martin-henz earlier and we think there's still potential for these two features to be revived sometime in the future (perhaps by a CP3108 team). Plus, these two features are not blocking any of our planned changes/migrations at the moment, so there's no strong reason to necessitate their removal in the short-term future.

**Comment by martin-henz** [comment]
That's great. Let's keep them around and try to revive next year.
