### ISSUE TITLE
CSE Machine: config should not be an enum

### ISSUE THREAD

**Issue by RichDom2185** [source-academy/frontend#2851]
The CSE machine config should be a simple object, whose values can just be called like `Config.someValue` instead of having to use `Number()` or `.toString()`.

Moreover, enums are also not appropriate for the config as the enum values should be unique.

**Comment by RichDom2185** [comment]
By "simple object", I mean something similar to our `Constants` object. To ensure immutability, one can use `Object.freeze`:

```ts
export const Config = Object.freeze({
  fontSize: 99999999,
  // ...
});
```

**Comment by CZX123** [comment]
I think using `as const` should be enough as TypeScript will prevent any mutations, as long as one doesn't mess with the types.

**Comment by RichDom2185** [comment]
`as const` works in the type world (ensures compile-time safety) but using `Object.freeze` would also guarantee this at runtime (as the object is frozen in JS in the browser).
