### ISSUE TITLE
Enhancement: Mobile Keyboard should allow users to scroll through keys.

### ISSUE THREAD

**Issue by Johnwz123** [source-academy/frontend#2872]
This is for the mobile keyboard docked on the right side on mobile screens.

Currently, users need to click a button on the far right to cycle through the list of keys. 

https://github.com/source-academy/frontend/assets/112536096/3098563c-d0d7-4744-a081-c9468af59166

It would be easier if users can simply scroll horizontally to move through the list of keys, which would be more convenient when they need to use different keys when typing their programs.

https://github.com/source-academy/frontend/assets/112536096/4783fdd8-d5a5-4fd9-a3b6-422e0e70839a

**Comment by RichDom2185** [comment]
Yes, I love the Repl.it mobile keyboard; we might need to move to a different library to get this functionality though. Are you familiar with any such libraries?
