### ISSUE TITLE
Editor: autocomplete does not follow alias

### ISSUE THREAD

**Issue by martin-henz** [source-academy/frontend#2907]
The autocomplete in the playground editor currently ignores the "as name" suffixes that can be appended to imported names. Examples:

<img width="990" alt="Screenshot 2024-04-08 at 9 09 46 AM" src="https://github.com/source-academy/frontend/assets/30220768/2bf2d28f-c13a-4e79-99aa-be1ba32f9532">

<img width="990" alt="Screenshot 2024-04-08 at 9 10 12 AM" src="https://github.com/source-academy/frontend/assets/30220768/f66f4a64-f9bf-4849-951f-d0bc078b4cf5">

I vaguely remember that this was working in the past, so I marked it as "regression".

**Comment by leeyi45** [comment]
<img width="744" alt="image" src="https://github.com/user-attachments/assets/0dc5f9b9-0ec1-4e60-98fb-863303039196">

This is working for me on sourceacademy.org

**Comment by martin-henz** [comment]
Great. This works again!
