### ISSUE TITLE
New module loading changes break loading in Firefox

### ISSUE THREAD

**Issue by josh1248** [source-academy/frontend#2912]
After updating to the commit at https://github.com/source-academy/frontend/pull/2904, the frontend is no longer loading properly for me, but only for my Firefox browser (124.0.2). Everything works fine when I tried loading it in Safari.

![image](https://github.com/source-academy/frontend/assets/110712708/23216aeb-ca0b-4050-994d-7c6897a9182e)

These are the network and console logs at this commit:

![image](https://github.com/source-academy/frontend/assets/110712708/60b1bc07-a53b-498c-aa97-01849daa38fd)
![image](https://github.com/source-academy/frontend/assets/110712708/94e51429-4b5c-47d9-8dfa-8906a93d4507)

These are the network and console logs before this commit:
![image](https://github.com/source-academy/frontend/assets/110712708/93633ebf-e7ce-4c82-bbd5-067da6bb0dcd)
![image](https://github.com/source-academy/frontend/assets/110712708/ee495a0b-c09b-4584-86a8-605a89df7aff)

Other things that may be relevant:
-Firefox 124.0.2
-Safari 16.6
-Macbook on M2 chip, ventura 13.5.2
-Python 2.7.18 used for gl build
-backend used = true under .env settings
-I note that this issue occurred while working on my pull request at https://github.com/source-academy/frontend/pull/2856, which I merged master into.

**Comment by sayomaki** [comment]
Resolved via source-academy/js-slang#1656
