### ISSUE TITLE
Assessment submissions can be modified, triggering unsubmission

### ISSUE THREAD

**Issue by josh1248** [source-academy/frontend#2913]
The 'save' feature seems to have been accidentally enabled for assessment submissions even after the submissions have been finalized. As a result, they can be modified, which automatically triggers an un-submission.

https://github.com/source-academy/frontend/assets/110712708/a84b20f4-f8fb-4a3d-ae9b-14bd3d394d19

**Comment by RichDom2185** [comment]
@josh1248 thanks for this report! Can you confirm which commit caused this? You said you checked till late Feb right?

**Comment by chownces** [comment]
Likely due to admin/ staff role. Could you guys check again with a student role?

https://github.com/source-academy/backend/blob/410905ac4595c3cc339a8d5fb224b355178f77af/lib/cadet_web/controllers/answer_controller.ex#L20

**Comment by josh1248** [comment]
Tested this using the students login and the save button didnt show up as intended... sorry for the trouble guys 😓

**Comment by josh1248** [comment]
I will close this (fake) issue and update the frontend developer wiki about this so this wouldnt happen again
