### ISSUE TITLE
Migrate hotkeys library 

### ISSUE THREAD

**Issue by chownces** [source-academy/frontend#2935]
Issue:
- Current library: https://www.npmjs.com/package/react-hotkeys
    -  No longer actively maintained
    - Unnecessary to have a separate hotkeys library when modern UI libraries provide this

Suggestions:
- Blueprint: https://blueprintjs.com/docs/#core/hooks/use-hotkeys
- @mantine/hooks: https://mantine.dev/hooks/use-hotkeys/

Initial thoughts:
- mantine's implementation looks a lot cleaner

**Comment by RichDom2185** [comment]
> * mantine's implementation looks a lot cleaner

Yes, not to mention it can also replicate the old behavior by simply defining a `Hotkeys` HOC with `getHotkeyHandler` from `@mantine/hooks`.

Also, it has a special key `mod` (modifier) that translates to `ctrl` on Windows and `cmd` on macOS automatically.

**Comment by RichDom2185** [comment]
Marking this as important as I feel we should try to minimise our dependencies as much as possible before migrating to Vite (which is also marked "important").

**Comment by chownces** [comment]
> Separately, even though https://www.npmjs.com/package/react-responsive is still maintained, Mantine Hooks also provides `useMediaQuery`

Let's track this in a separate issue: #2967
