### ISSUE TITLE
Mission briefing for grading workspace

### ISSUE THREAD

**Issue by remo5000** [source-academy/frontend#310]
Received feedback from a colleague that this would be useful when grading an assessment.

**Comment by Aulud** [comment]
Addressed by #921.

**Comment by Aulud** [comment]
Have discussed this with @geshuming and agreed on a more substantial fix during the recess week that changes the interface for retrieving grading submissions between the frontend and backend.

**Comment by martin-henz** [comment]
Subsumed by #2310
