### ISSUE TITLE
should globals property of Library in components/assessment/assessmentShape.ts be put to use?

### ISSUE THREAD

**Issue by gerhean** [source-academy/frontend#453]
in update-js-lang branch:
cadet-frontend\src\mocks\assessmentAPI.ts

the mockGlobals defined do not load in source academy mock missions (An Odessey to Runes) in the workspace

**Comment by openorclose** [comment]
Is there any error that occurs?

**Comment by gerhean** [comment]
No error message

**Comment by openorclose** [comment]
Can you try it on master, js-slang 0.1.19? I tried typing testNumber, testString etc in the REPL and it did not work as well.

**Comment by openorclose** [comment]
Turns out the globals property is not being used by anything, that's why they're not working.

**Comment by gerhean** [comment]
Then should it be implemented?

**Comment by martin-henz** [comment]
Obsolete: No more "libraries": we have "modules" now.
