### ISSUE TITLE
Help text should be configurable, at the time of deployment

### ISSUE THREAD

**Issue by martin-henz** [source-academy/frontend#547]
The current help text is very specific and hard-wired into the sources of the Source Academy:

**Please use the following resources when you encounter issues with this system.**

**For critical technical issues that seriously affect your learning experience, email the Technical Services of the NUS School of Computing at techsvc@comp.nus.edu.sg or call 6516 2736.**
**For non-critical technical issues, such as enhancement suggestions, please use the issue system of the Source Academy repositories on GitHub.**
**For issues related to the content of missions, quests, paths and contests, use the respective forum at piazza, or approach your Avenger, Reflection instructor or lecturer.**

**Comment by chownces** [comment]
Addressed by #1878
