### ISSUE TITLE
DEBUG: causing issues in for loop

### ISSUE THREAD

**Issue by openorclose** [source-academy/frontend#595]
```
const a = [];
for (let i = 0; i < 10; i = i + 1) {
    const j = () => i;
    a[i] = j;
    debugger;
}
```

Running this code then pressing resume causes an error:

```
Line 4: Cannot assign new value to constant i.
```

But commenting out the debugger line, the code executes just fine.

**Comment by martin-henz** [comment]
<img width="1009" alt="Screenshot 2021-12-12 at 9 33 48 PM" src="https://user-images.githubusercontent.com/30220768/145714497-cee1ac2c-29a3-4ee9-8465-0c484e3832dc.png">
 
Works properly now.
