### ISSUE TITLE
Debugger: Resuming a paused program gives unexpected errors

### ISSUE THREAD

**Issue by alcen** [source-academy/frontend#704]
Expected behaviour:
The program runs until just before the selected line.
When the program is resumed, the program is run to the end.

Current behaviour:
When the program is resumed, the selected line is run in the wrong scope, leading to errors such as `Line 6: Redeclaring name i.` or `Line 11: Name a1 not declared.`

How to reproduce:
1. Copy and paste this code in the playground
```
function a(param1, param2) {
    const x = "abc";
    const y = list;
    
    function b() {
        const i = 1;
        a1();
    }
    
    function c() {
        const y = a1;
        const z = list(1, list(2, 3));
        const z1 = list(2, 3);
        b();


    }
    
    c();
}

function a1() {
    const test_param = 1;
    return 2;
}
const x = 1;
a(pair, is_list);
```
2. Select Line 6 or Line 11 on the left
3. Run the program - the debugger gets activated and the output is `"Breakpoint hit!"`
4. Select resume
5. An error is thrown: `Line 6: Redeclaring name i.` or `Line 11: Name a1 not declared.`

Screenshots:
![line6](https://user-images.githubusercontent.com/49450743/61069240-6ae79400-a43e-11e9-8981-1ac12ea847f8.png)
![line11](https://user-images.githubusercontent.com/49450743/61069249-70dd7500-a43e-11e9-84b9-af278d0b47d2.png)

**Comment by martin-henz** [comment]
debugger has been removed
