### ISSUE TITLE
Swiping gesture in Chrome leads to loss of program

### ISSUE THREAD

**Issue by martin-henz** [source-academy/frontend#726]
<img width="424" alt="Screenshot 2019-07-15 at 10 09 06 PM" src="https://user-images.githubusercontent.com/30220768/61222470-59a7cb80-a74d-11e9-80b4-30ddd7b58d9a.png">

This used to happen to me quite frequently: I accidentally swipe on the screen (on the mac with two fingers). This white arrow appears and I go to the previous page that was visited in the current browser tab. By that, I lose my recent edits.

**Comment by martin-henz** [comment]
Seems to be a common thing on the mac. Here is the solution:

System Preferences > Trackpad > More Gestures > Under “Swipe between pages” just uncheck that box.

We could put this in the module FAQ? Any other suggestions, anyone?

**Comment by alcen** [comment]
It seems like Chrome has this [tab discarding feature](https://developers.google.com/web/updates/2015/09/tab-discarding) where tabs are reloaded to save on memory. This should only occur when many tabs are open though

I found several complaints about this behaviour (like https://support.google.com/chrome/thread/4464367?hl=en) online. Apparently Google recently removed the ability to disable this in Chrome 75, and one solution is to install this add-on: https://chrome.google.com/webstore/detail/disable-automatic-tab-dis/dnhngfnfolbmhgealdpolmhimnoliiok

Probably we could add a reminder to save frequently if there are many tabs open?

**Comment by martin-henz** [comment]
> It seems like Chrome has this [tab discarding feature](https://developers.google.com/web/updates/2015/09/tab-discarding) where tabs are reloaded to save on memory. This should only occur when many tabs are open though
> 
> I found several complaints about this behaviour (like https://support.google.com/chrome/thread/4464367?hl=en) online. Apparently Google recently removed the ability to disable this in Chrome 75, and one solution is to install this add-on: https://chrome.google.com/webstore/detail/disable-automatic-tab-dis/dnhngfnfolbmhgealdpolmhimnoliiok
> 
> Probably we could add a reminder to save frequently if there are many tabs open?

Not sure how closely related this is. Are we referring to the same thing?

**Comment by martin-henz** [comment]
Does the swipe problem arise in Windows or Linux, or is this a mac-specific issue?

**Comment by alcen** [comment]
> It seems like Chrome has this tab discarding feature where tabs are reloaded to save on memory. This should only occur when many tabs are open though
> I found several complaints about this behaviour (like https://support.google.com/chrome/thread/4464367?hl=en) online. Apparently Google recently removed the ability to disable this in Chrome 75, and one solution is to install this add-on: https://chrome.google.com/webstore/detail/disable-automatic-tab-dis/dnhngfnfolbmhgealdpolmhimnoliiok
> Probably we could add a reminder to save frequently if there are many tabs open?
> 
> Not sure how closely related this is. Are we referring to the same thing?

Oh, I thought the original issue was about tab switching by mistake? This might have led to the discarding of the program


> Does the swipe problem arise in Windows or Linux, or is this a mac-specific issue?

Seems like it is a Mac issue with the touch gestures. However it might be possible to set up Chrome on Windows laptops to support the gestures. Using the "Back" button on the browser does give a prompt that "You have changes that may not be saved" though, to prevent unsaved programs from being discarded, if that is not the case with the touch gestures then it may be a problem with Google Chrome?

**Comment by martin-henz** [comment]
> Using the "Back" button on the browser does give a prompt that "You have changes that may not be saved" though, to prevent unsaved programs from being discarded, if that is not the case with the touch gestures then it may be a problem with Google Chrome?

Yes, this prompt does not appear when using the gesture. The problem appears when trying to use a gesture to scroll in the editor. 

To reproduce: make the editor narrow so that not all text is seen. Now you can scroll on the mac using two fingers. Not sure how this works in Windows. When the display hits the left margin, the scrolling switches to the Chrome back button: You go to the previously visited page.

It would be good if we could catch this within our application: Can we keep the focus of the scrolling on the editor, even when we hit the left margin?

**Comment by alcen** [comment]
> Yes, this prompt does not appear when using the gesture. The problem appears when trying to use a gesture to scroll in the editor.

In that case, there may be an issue with the prompt. I have done some investigation and the prompt does not show up if you type an URL into the address bar of the browser and navigate to another webpage. This is an unresolved issue with the prompt that we use: https://github.com/ReactTraining/react-router/issues/6830

Using the refresh button and the home button does not display the prompt either. On Chrome, if I click the browser's "Back"  button, the navigation occurs even with the prompt, and when I select "Cancel" I am still led to the previous page.

Overall, the only time the prompt consistently appears is if I navigate to another page within the Source Academy website.
&nbsp;
> It would be good if we could catch this within our application: Can we keep the focus of the scrolling on the editor, even when we hit the left margin?

I feel like we should be looking at fixing the "You have unsaved changes" prompt, instead of trying to disable the swiping gesture which students may be accustomed to. That may be a more focused solution to the key problem of programs being discarded on accident, rather than trying to restrict inherent browser/OS features. To me it seems very arbitrary to restrict the scrolling, and there could be unintended side effects on other browsers as a result of doing so.

**Comment by martin-henz** [comment]
> > Yes, this prompt does not appear when using the gesture. The problem appears when trying to use a gesture to scroll in the editor.
> 
> In that case, there may be an issue with the prompt. I have done some investigation and the prompt does not show up if you type an URL into the address bar of the browser and navigate to another webpage. This is an unresolved issue with the prompt that we use: [ReactTraining/react-router#6830](https://github.com/ReactTraining/react-router/issues/6830)
> 
> Using the refresh button and the home button does not display the prompt either. On Chrome, if I click the browser's "Back" button, the navigation occurs even with the prompt, and when I select "Cancel" I am still led to the previous page.
> 
> Overall, the only time the prompt consistently appears is if I navigate to another page within the Source Academy website.
>  
> 
> > It would be good if we could catch this within our application: Can we keep the focus of the scrolling on the editor, even when we hit the left margin?
> 
> I feel like we should be looking at fixing the "You have unsaved changes" prompt, instead of trying to disable the swiping gesture which students may be accustomed to. That may be a more focused solution to the key problem of programs being discarded on accident, rather than trying to restrict inherent browser/OS features. To me it seems very arbitrary to restrict the scrolling, and there could be unintended side effects on other browsers as a result of doing so.

I agree. Seems like a deeper issue, and disabling the swiping would attempt to fix a symptom rather than the cause.

Thanks for looking into this!
