### ISSUE TITLE
Grading does not prompt for "save" in case of no change

### ISSUE THREAD

**Issue by martin-henz** [source-academy/frontend#736]
If the grader accepts the autograde result and does not change the grade, the "Next" button does not prompt for "save". However, the question retains the status "ungraded". 

Fix: prompt to "save" or "mark as graded?" even when there is no change.

**Comment by geshuming** [comment]
Ok. This can be a purely frontend fix.

**Comment by geshuming** [comment]
Fix: Submit empty grading info to backend. It will still count as "graded"

**Comment by martin-henz** [comment]
Do you suggest we don't prompt to "save" in the case where the grader leaves the question without pressing "Save"? Can you clarify what fix you suggest?

**Comment by geshuming** [comment]
I think we should be more specific with the actions available. The word `Save` is misused here. I think a better word will be `Submit Grading` or `Submit Adjustments` or `Confirm Grading`.

**Comment by geshuming** [comment]
I think the best term to use is `Confirm Review` or `Confirm Grades`. `Save` implies new changes, which graders might not make.
