### ISSUE TITLE
Grading table should remember and run last filter setting

### ISSUE THREAD

**Issue by martin-henz** [source-academy/frontend#737]
<img width="253" alt="Screenshot 2019-07-18 at 10 54 37 AM" src="https://user-images.githubusercontent.com/30220768/61425743-8b39b600-a94a-11e9-9238-c086c2326e03.png">

Currently, the grading table has no memory of previous filter setting. I think it should remember and run the previous filter setting when re-visiting the table.

**Comment by geshuming** [comment]
Understood. This is rather important
