### ISSUE TITLE
Grading: "Save" allows students to access unfinished grades

### ISSUE THREAD

**Issue by alcen** [source-academy/frontend#799]
Sometimes, grading can take a while or involve multiple graders, and graders will save their work to the database to resume grading at a later time. However, this actually exposes the unfinished work to the students as well.

They may get confused when their grades change constantly, so making grades available for students to view should feel more permanent, especially with the notification system. Once the grades are made available for view by the students, changes should only be made if there is a good reason to, like to fix mistakes or to carry out changes in the marking scheme

Refer to the discussion on pull request #789 and issue #739

**Comment by martin-henz** [comment]
Correct. The team discussed this and decided that we keep the commenting simple for now, and revisit this after Sem 1 AY2019/20. So we'll mark this issue as _postponed.
