### ISSUE TITLE
Use git submodules to import external libraries

### ISSUE THREAD

**Issue by geshuming** [source-academy/frontend#802]
Title. 

Git submodules allow us to separate external library code into its own repo, creating a single source of truth while allowing testing to be done

**Comment by martin-henz** [comment]
Good idea for the coming semester. Don't have anyone in charge of any of the libraries, with the exception of Iskandar perhaps, for SOUNDS. So RUNES and CURVES are a bit orphaned. I tried to improve them, but didn't get around to write tests.

**Comment by martin-henz** [comment]
We may not have time for this in 2019.

**Comment by martin-henz** [comment]
modules are now handled with the modules repo. So this is obsolete.
