### ISSUE TITLE
Refactor evalCode saga for Autograder run-all functionality

### ISSUE THREAD

**Issue by Aulud** [source-academy/frontend#812]
## Refactor evalCode saga for Autograder run-all functionality
Summary: Deferred refactoring to continue support for Mission Autograder run-all functionality from #801.

### Todos
- Remove `sideContentActiveTab` attribute from Redux store along with the associated action `UPDATE_ACTIVE_TAB` with its action creator and reducer, in line with the project to clean up the Redux state tree
- Remove conditional behaviour in `evalCode` saga for run-all testcase functionality
- Re-implement run-all testcase functionality in line with #607 by constructing a different 'Run' button in assessment and grading workspaces, to be passed to `ControlBar`
   - This button will contain its own internal `activeTab` prop inherited from the state of the containing workspace, and will invoke either `EVAL_EDITOR` or `EVAL_EDITOR_WITH_TESTCASES` depending on the value of its `activeTab` prop
   - `activeTab` state of the containing workspace will be updated by the `onChange` handler of the respective workspace's `SideContent` component
- Add a new action `EVAL_EDITOR_WITH_TESTCASES` with its action creator, reducer and saga to be invoked by the alternative 'Run' button
- Repair all broken tests from the refactor

**Comment by chownces** [comment]
Addressed by #1860
