### ISSUE TITLE
Unable to draw curves when selecting 'All' libraries

### ISSUE THREAD

**Issue by iskandarzulkarnaien** [source-academy/frontend#848]
Curves fail to draw with the error message "Error: Please activate the Canvas component by clicking it in the sidebar". This only occurs when selecting "All" libraries. Selecting "Curves" before or after "All" prevents / fixes this error.

**Comment by chownces** [comment]
Closing this as the curves library has been shifted over to the new modules system, and is no longer available in the Playground dropdown menu.
