### ISSUE TITLE
SOUNDS: Display waveform function is not very useful

### ISSUE THREAD

**Issue by geshuming** [source-academy/frontend#935]
```
const sound1 = sine_sound(25, 1);
const sound2 = noise_sound(1);

function add_sounds(sound1, sound2) {
    [redacted]
}

display_waveform(500, add_sounds(sound1, sound2));
```

The above code produces the image below:
![image](https://user-images.githubusercontent.com/43642522/64861162-df6ac900-d661-11e9-892b-ed4a1804ec2b.png)

Sounds of greater duration/frequency creates blocky images like below:
![image](https://user-images.githubusercontent.com/43642522/64861349-4ab49b00-d662-11e9-9c35-c1de90c91372.png)

Suggestion 1) the curve should ideally span the left edge to the right edge
2) Is there a way to "slice" the waveform, or something?
3) For future consideration: Animation, animating of the waveform can help alot.

**Comment by geshuming** [comment]
```
const sound1 = sine_sound(10, 0.5);
const sound2 = square_sound(10, 0.5);
const sound3 = triangle_sound(10, 0.5);

function add_sounds(sound1, sound2) {
    [redacted]
}

function display_waveform(num_points_per_second, sound) {
    let wave = get_wave(sound);
    let duration = get_duration(sound);
    let num_points = num_points_per_second * duration;
    return draw_connected_full_view(num_points)(t => pair(t, wave(duration * t)));
}

display_waveform(5000, add_sounds(add_sounds(sound1, sound2), sound3));
```

The above code produces the below image. Note the overriden `display_waveform`

![image](https://user-images.githubusercontent.com/43642522/64862381-f363fa00-d664-11e9-95cd-da4ea8f655e3.png)

**Comment by martin-henz** [comment]
Display waveform is useful for showing ADSR envelopes.

**Comment by martin-henz** [comment]
moved to modules: https://github.com/source-academy/modules/issues/120
